postgresql: &postgresql
  adapter: postgresql
  database: <%=ENV['POSTGRESQL_DATABASE']%>
  username: <%=ENV['POSTGRESQL_USER']%>
  password: <%=ENV['POSTGRESQL_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  min_messages: ERROR
  reconnect: false

defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "postgresql" %>

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
